[package]
name = "fido2luks"
version = "0.1.0"
authors = ["shimunn <shimun@shimun.net>"]
edition = "2018"

[dependencies]
ctap = { git = "https://github.com/shimunn/ctap.git", branch = "hmac_ext" }
#cryptsetup-rs = "0.2.0"
cryptsetup-rs = { git = "https://github.com/shimunn/cryptsetup-rs.git", branch = "update_keyslot" }
libcryptsetup-sys = { git = "https://github.com/shimunn/cryptsetup-rs.git", branch = "update_keyslot" }

hex = "0.3.2"
rust-crypto = "0.2.36"
failure = "0.1.5"
rpassword = "4.0.1"
structopt = "0.3.2"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
incremental = false
overflow-checks = false
