[package]
name = "fido2luks"
version = "0.1.0"
authors = ["shimunn <shimun@shimun.net>"]
edition = "2018"

[dependencies]
ctap = { git = "https://git.shimun.net/shimun/ctap.git", branch = "hmac_ext" }
cryptsetup-rs = "0.2.0"
hex = "0.3.2"
rust-crypto = "0.2.36"
failure = "0.1.5"
serde_derive = "1.0.100"
serde = "1.0.100"
serde_json = "1.0.40"
keyutils = "0.2.1"
rpassword = "4.0.1"


[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
